"""Update project with dates 2

Revision ID: 616bead2342a
Revises: de3468f5445a
Create Date: 2025-03-26 14:29:23.184495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '616bead2342a'
down_revision: Union[str, None] = 'de3468f5445a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('complete_date', sa.Date(), nullable=True))
    op.drop_column('projects', 'board')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('board', postgresql.ENUM('todo', 'in_progress', 'completed', name='projectboard'), autoincrement=False, nullable=True))
    op.drop_column('projects', 'complete_date')
    op.drop_column('projects', 'due_date')
    # ### end Alembic commands ###
