"""Update project with board

Revision ID: f39ca4ebfad5
Revises: 616bead2342a
Create Date: 2025-03-26 14:33:11.928377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f39ca4ebfad5'
down_revision: Union[str, None] = '616bead2342a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('board', sa.Enum('todo', 'in_progress', 'completed', name='projectboard'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'board')
    # ### end Alembic commands ###
