"""Update habit structure 2

Revision ID: f5efaeb99e70
Revises: f75f1e9f6696
Create Date: 2025-03-25 18:22:52.879339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5efaeb99e70'
down_revision: Union[str, None] = 'f75f1e9f6696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('color', sa.String(), nullable=True))
    op.drop_column('habits', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('habits', 'color')
    # ### end Alembic commands ###
