"""Update project

Revision ID: fa26d58eeaaf
Revises: f5efaeb99e70
Create Date: 2025-03-26 14:07:01.024406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa26d58eeaaf'
down_revision: Union[str, None] = 'f5efaeb99e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE projectpriority AS ENUM ('low', 'high', 'completed')")
    op.execute("CREATE TYPE projectboard AS ENUM ('todo', 'in_progress', 'completed')")
    op.add_column('projects', sa.Column('description', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('priority', sa.Enum('low', 'high', 'completed', name='projectpriority'), nullable=True))
    op.add_column('projects', sa.Column('board', sa.Enum('todo', 'in_progress', 'completed', name='projectboard'), nullable=True))
    op.drop_column('projects', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'board')
    op.drop_column('projects', 'priority')
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
