version: "3.9"

services:
  backend:
    build: ./TaskManager_back
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./task-manager-client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: